/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChat: typeof import('./components/AiChat.vue')['default']
    AiDraftPanel: typeof import('./components/common/AiDraftPanel.vue')['default']
    AiInputBox: typeof import('./components/common/AiInputBox.vue')['default']
    BubblesAiView: typeof import('./components/BubblesAiView.vue')['default']
    BubblesLogo: typeof import('./components/common/BubblesLogo.vue')['default']
    ChatFocusView: typeof import('./components/ChatFocusView.vue')['default']
    ChatSessionsView: typeof import('./components/ChatSessionsView.vue')['default']
    ComposeFields: typeof import('./components/compose/ComposeFields.vue')['default']
    ComposeToolbar: typeof import('./components/compose/ComposeToolbar.vue')['default']
    ComposeView: typeof import('./components/ComposeView.vue')['default']
    DailyDigest: typeof import('./components/DailyDigest.vue')['default']
    DashboardLayout: typeof import('./components/DashboardLayout.vue')['default']
    EmailDetail: typeof import('./components/EmailDetail.vue')['default']
    EmailList: typeof import('./components/EmailList.vue')['default']
    LeftPanel: typeof import('./components/LeftPanel.vue')['default']
    MiddlePanel: typeof import('./components/MiddlePanel.vue')['default']
    RightPanel: typeof import('./components/RightPanel.vue')['default']
    SettingsAccountsTab: typeof import('./components/settings/SettingsAccountsTab.vue')['default']
    SettingsAgentTab: typeof import('./components/settings/SettingsAgentTab.vue')['default']
    SettingsAiTab: typeof import('./components/settings/SettingsAiTab.vue')['default']
    SettingsDetailView: typeof import('./components/SettingsDetailView.vue')['default']
    SettingsSecurityTab: typeof import('./components/settings/SettingsSecurityTab.vue')['default']
    SettingsSidebar: typeof import('./components/SettingsSidebar.vue')['default']
    SettingsSystemTab: typeof import('./components/settings/SettingsSystemTab.vue')['default']
    Versions: typeof import('./components/Versions.vue')['default']
  }
}
